// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client'

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] }

type HomeDocumentDataSlicesSlice =
    | HomeHeroSlice
    | HomeAboutSlice
    | HomeBackgroundSlice
    | HomeProjectsSlice

/**
 * Content for Home documents
 */
interface HomeDocumentData {
    /**
     * Slice Zone field in *Home*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: home.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#slices
     */
    slices: prismic.SliceZone<HomeDocumentDataSlicesSlice>
    /**
     * Meta Description field in *Home*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A brief summary of the page
     * - **API ID Path**: home.meta_description
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    meta_description: prismic.KeyTextField

    /**
     * Meta Image field in *Home*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: home.meta_image
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    meta_image: prismic.ImageField<never>

    /**
     * Meta Title field in *Home*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A title of the page used for social media and search engines
     * - **API ID Path**: home.meta_title
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    meta_title: prismic.KeyTextField
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
    prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, 'home', Lang>

/**
 * Item in *imageList → images*
 */
export interface ImagelistDocumentDataImagesItem {
    /**
     * image field in *imageList → images*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: imagelist.images[].image
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    image: prismic.ImageField<never>
}

/**
 * Content for imageList documents
 */
interface ImagelistDocumentData {
    /**
     * images field in *imageList*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: imagelist.images[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#group
     */
    images: prismic.GroupField<Simplify<ImagelistDocumentDataImagesItem>>
}

/**
 * imageList document from Prismic
 *
 * - **API ID**: `imagelist`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ImagelistDocument<Lang extends string = string> =
    prismic.PrismicDocumentWithUID<
        Simplify<ImagelistDocumentData>,
        'imagelist',
        Lang
    >

/**
 * Item in *Navigation → links*
 */
export interface NavigationDocumentDataLinksItem {
    /**
     * text field in *Navigation → links*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.links[].text
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    text: prismic.KeyTextField

    /**
     * value field in *Navigation → links*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.links[].value
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    value: prismic.KeyTextField
}

type NavigationDocumentDataSlicesSlice = never

/**
 * Content for Navigation documents
 */
interface NavigationDocumentData {
    /**
     * img field in *Navigation*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.img
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    img: prismic.ImageField<never>

    /**
     * links field in *Navigation*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.links[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#group
     */
    links: prismic.GroupField<Simplify<NavigationDocumentDataLinksItem>>

    /**
     * buttonText field in *Navigation*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.buttontext
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    buttontext: prismic.KeyTextField

    /**
     * buttonImg field in *Navigation*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.buttonimg
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    buttonimg: prismic.ImageField<never>

    /**
     * file field in *Navigation*
     *
     * - **Field Type**: Link to Media
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.file
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
     */
    file: prismic.LinkToMediaField

    /**
     * Slice Zone field in *Navigation*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#slices
     */
    slices: prismic.SliceZone<NavigationDocumentDataSlicesSlice>
    /**
     * Meta Description field in *Navigation*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A brief summary of the page
     * - **API ID Path**: navigation.meta_description
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    meta_description: prismic.KeyTextField

    /**
     * Meta Image field in *Navigation*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.meta_image
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    meta_image: prismic.ImageField<never>

    /**
     * Meta Title field in *Navigation*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A title of the page used for social media and search engines
     * - **API ID Path**: navigation.meta_title
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    meta_title: prismic.KeyTextField
}

/**
 * Navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> =
    prismic.PrismicDocumentWithoutUID<
        Simplify<NavigationDocumentData>,
        'navigation',
        Lang
    >

/**
 * Item in *textList → list*
 */
export interface TextlistDocumentDataListItem {
    /**
     * text field in *textList → list*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: textlist.list[].text
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    text: prismic.KeyTextField
}

/**
 * Content for textList documents
 */
interface TextlistDocumentData {
    /**
     * list field in *textList*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: textlist.list[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#group
     */
    list: prismic.GroupField<Simplify<TextlistDocumentDataListItem>>
}

/**
 * textList document from Prismic
 *
 * - **API ID**: `textlist`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TextlistDocument<Lang extends string = string> =
    prismic.PrismicDocumentWithUID<
        Simplify<TextlistDocumentData>,
        'textlist',
        Lang
    >

/**
 * Item in *TitleDescDateImageList → list*
 */
export interface TitledescdateimagelistDocumentDataListItem {
    /**
     * title field in *TitleDescDateImageList → list*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: titledescdateimagelist.list[].title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField

    /**
     * desc field in *TitleDescDateImageList → list*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: titledescdateimagelist.list[].desc
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    desc: prismic.KeyTextField

    /**
     * date field in *TitleDescDateImageList → list*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: titledescdateimagelist.list[].date
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    date: prismic.KeyTextField

    /**
     * dateImage field in *TitleDescDateImageList → list*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: titledescdateimagelist.list[].dateimage
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    dateimage: prismic.ImageField<never>

    /**
     * imageList field in *TitleDescDateImageList → list*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: titledescdateimagelist.list[].imagelist
     * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
     */
    imagelist: prismic.ContentRelationshipField
}

/**
 * Content for TitleDescDateImageList documents
 */
interface TitledescdateimagelistDocumentData {
    /**
     * title field in *TitleDescDateImageList*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: titledescdateimagelist.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField

    /**
     * img field in *TitleDescDateImageList*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: titledescdateimagelist.img
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    img: prismic.ImageField<never>

    /**
     * list field in *TitleDescDateImageList*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: titledescdateimagelist.list[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#group
     */
    list: prismic.GroupField<
        Simplify<TitledescdateimagelistDocumentDataListItem>
    >
}

/**
 * TitleDescDateImageList document from Prismic
 *
 * - **API ID**: `titledescdateimagelist`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TitledescdateimagelistDocument<Lang extends string = string> =
    prismic.PrismicDocumentWithUID<
        Simplify<TitledescdateimagelistDocumentData>,
        'titledescdateimagelist',
        Lang
    >

export type AllDocumentTypes =
    | HomeDocument
    | ImagelistDocument
    | NavigationDocument
    | TextlistDocument
    | TitledescdateimagelistDocument

/**
 * Primary content in *HomeAbout → Primary*
 */
export interface HomeAboutSliceDefaultPrimary {
    /**
     * title field in *HomeAbout → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home_about.primary.title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField

    /**
     * name field in *HomeAbout → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home_about.primary.name
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    name: prismic.KeyTextField

    /**
     * info field in *HomeAbout → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home_about.primary.info
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    info: prismic.KeyTextField

    /**
     * img field in *HomeAbout → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: home_about.primary.img
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    img: prismic.ImageField<never>

    /**
     * desc field in *HomeAbout → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home_about.primary.desc
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    desc: prismic.KeyTextField
}

/**
 * Primary content in *HomeAbout → Items*
 */
export interface HomeAboutSliceDefaultItem {
    /**
     * title field in *HomeAbout → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home_about.items[].title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField

    /**
     * num field in *HomeAbout → Items*
     *
     * - **Field Type**: Number
     * - **Placeholder**: *None*
     * - **API ID Path**: home_about.items[].num
     * - **Documentation**: https://prismic.io/docs/field#number
     */
    num: prismic.NumberField

    /**
     * suffix field in *HomeAbout → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home_about.items[].suffix
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    suffix: prismic.KeyTextField
}

/**
 * Default variation for HomeAbout Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeAboutSliceDefault = prismic.SharedSliceVariation<
    'default',
    Simplify<HomeAboutSliceDefaultPrimary>,
    Simplify<HomeAboutSliceDefaultItem>
>

/**
 * Slice variation for *HomeAbout*
 */
type HomeAboutSliceVariation = HomeAboutSliceDefault

/**
 * HomeAbout Shared Slice
 *
 * - **API ID**: `home_about`
 * - **Description**: HomeAbout
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeAboutSlice = prismic.SharedSlice<
    'home_about',
    HomeAboutSliceVariation
>

/**
 * Primary content in *HomeBackground → Primary*
 */
export interface HomeBackgroundSliceDefaultPrimary {
    /**
     * title field in *HomeBackground → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home_background.primary.title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField
}

/**
 * Primary content in *HomeBackground → Items*
 */
export interface HomeBackgroundSliceDefaultItem {
    /**
     * list field in *HomeBackground → Items*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: home_background.items[].list
     * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
     */
    list: prismic.ContentRelationshipField
}

/**
 * Default variation for HomeBackground Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeBackgroundSliceDefault = prismic.SharedSliceVariation<
    'default',
    Simplify<HomeBackgroundSliceDefaultPrimary>,
    Simplify<HomeBackgroundSliceDefaultItem>
>

/**
 * Slice variation for *HomeBackground*
 */
type HomeBackgroundSliceVariation = HomeBackgroundSliceDefault

/**
 * HomeBackground Shared Slice
 *
 * - **API ID**: `home_background`
 * - **Description**: HomeBackground
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeBackgroundSlice = prismic.SharedSlice<
    'home_background',
    HomeBackgroundSliceVariation
>

/**
 * Primary content in *HomeHero → Primary*
 */
export interface HomeHeroSliceDefaultPrimary {
    /**
     * title field in *HomeHero → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home_hero.primary.title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField

    /**
     * img field in *HomeHero → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: home_hero.primary.img
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    img: prismic.ImageField<never>

    /**
     * descs field in *HomeHero → Primary*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: home_hero.primary.descs
     * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
     */
    descs: prismic.ContentRelationshipField

    /**
     * descSuffix field in *HomeHero → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home_hero.primary.descsuffix
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    descsuffix: prismic.KeyTextField
}

/**
 * Primary content in *HomeHero → Items*
 */
export interface HomeHeroSliceDefaultItem {
    /**
     * buttonText field in *HomeHero → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home_hero.items[].buttontext
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    buttontext: prismic.KeyTextField

    /**
     * buttonLink field in *HomeHero → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home_hero.items[].buttonlink
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    buttonlink: prismic.KeyTextField
}

/**
 * Default variation for HomeHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeHeroSliceDefault = prismic.SharedSliceVariation<
    'default',
    Simplify<HomeHeroSliceDefaultPrimary>,
    Simplify<HomeHeroSliceDefaultItem>
>

/**
 * Slice variation for *HomeHero*
 */
type HomeHeroSliceVariation = HomeHeroSliceDefault

/**
 * HomeHero Shared Slice
 *
 * - **API ID**: `home_hero`
 * - **Description**: HomeHero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeHeroSlice = prismic.SharedSlice<
    'home_hero',
    HomeHeroSliceVariation
>

/**
 * Primary content in *HomeProjects → Primary*
 */
export interface HomeProjectsSliceDefaultPrimary {
    /**
     * title field in *HomeProjects → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home_projects.primary.title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField
}

/**
 * Primary content in *HomeProjects → Items*
 */
export interface HomeProjectsSliceDefaultItem {
    /**
     * img field in *HomeProjects → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: home_projects.items[].img
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    img: prismic.ImageField<never>

    /**
     * link field in *HomeProjects → Items*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: home_projects.items[].link
     * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
     */
    link: prismic.LinkField
}

/**
 * Default variation for HomeProjects Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeProjectsSliceDefault = prismic.SharedSliceVariation<
    'default',
    Simplify<HomeProjectsSliceDefaultPrimary>,
    Simplify<HomeProjectsSliceDefaultItem>
>

/**
 * Slice variation for *HomeProjects*
 */
type HomeProjectsSliceVariation = HomeProjectsSliceDefault

/**
 * HomeProjects Shared Slice
 *
 * - **API ID**: `home_projects`
 * - **Description**: HomeProjects
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeProjectsSlice = prismic.SharedSlice<
    'home_projects',
    HomeProjectsSliceVariation
>

declare module '@prismicio/client' {
    interface CreateClient {
        (
            repositoryNameOrEndpoint: string,
            options?: prismic.ClientConfig
        ): prismic.Client<AllDocumentTypes>
    }

    namespace Content {
        export type {
            HomeDocument,
            HomeDocumentData,
            HomeDocumentDataSlicesSlice,
            ImagelistDocument,
            ImagelistDocumentData,
            ImagelistDocumentDataImagesItem,
            NavigationDocument,
            NavigationDocumentData,
            NavigationDocumentDataLinksItem,
            NavigationDocumentDataSlicesSlice,
            TextlistDocument,
            TextlistDocumentData,
            TextlistDocumentDataListItem,
            TitledescdateimagelistDocument,
            TitledescdateimagelistDocumentData,
            TitledescdateimagelistDocumentDataListItem,
            AllDocumentTypes,
            HomeAboutSlice,
            HomeAboutSliceDefaultPrimary,
            HomeAboutSliceDefaultItem,
            HomeAboutSliceVariation,
            HomeAboutSliceDefault,
            HomeBackgroundSlice,
            HomeBackgroundSliceDefaultPrimary,
            HomeBackgroundSliceDefaultItem,
            HomeBackgroundSliceVariation,
            HomeBackgroundSliceDefault,
            HomeHeroSlice,
            HomeHeroSliceDefaultPrimary,
            HomeHeroSliceDefaultItem,
            HomeHeroSliceVariation,
            HomeHeroSliceDefault,
            HomeProjectsSlice,
            HomeProjectsSliceDefaultPrimary,
            HomeProjectsSliceDefaultItem,
            HomeProjectsSliceVariation,
            HomeProjectsSliceDefault,
        }
    }
}
