// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic'

export const components = {
    home_about: dynamic(() => import('./HomeAbout')),
    home_background: dynamic(() => import('./HomeBackground')),
    home_hero: dynamic(() => import('./HomeHero')),
    home_projects: dynamic(() => import('./HomeProjects')),
}
