import { createClient } from '@/prismicio'
import './globals.css'
import type { Metadata } from 'next'
import Header from '@/components/header'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    const client = createClient()
    const page = await client.getSingle('navigation')
    return (
        <html lang="en">
            <body>
                <div className="flex flex-col items-center w-full overflow-hidden">
                    <Header data={page.data} />
                    {children}
                </div>
            </body>
        </html>
    )
}
